### ISSUE TITLE
debug mode do vector query Asserion triggered

### ISSUE THREAD

**Issue by adderllyer** [duckdb/duckdb_vss#39]
**vss verision**: v1.1.2
**duckdb version**:  v1.1-eatoni

with debug mode: make debug

and run sql example:
CREATE TABLE my_vector_table (vec FLOAT[3]);
INSERT INTO my_vector_table SELECT array_value(a,b,c) FROM range(1,10) ra(a), range(1,10) rb(b), range(1,10) rc(c);
CREATE INDEX my_hnsw_index ON my_vector_table USING HNSW (vec);

then do query as follow and error happened:
SELECT * FROM my_vector_table ORDER BY array_distance(vec, [1,2,3]::FLOAT[3]) LIMIT 3;

error info:
INTERNAL Error: Asserion triggered in file "..../duckdb/src/include/duckedb/common/help.hpp" on line 256

**Comment by Maxxen** [comment]
I don't think running extensions that are compiled for a different version of DuckDB is supported or even expected to work. I suppose the exception is thrown in "helper.hpp", which deals with dynamic type casts, so I would expect that this issue is due to the abi/rtti simply being different between the two binaries, because the duckdb version mismatches.

Either way, this does not reproduce on main if the vss extension is compiled with a matching duckdb version.

**Comment by Maxxen** [comment]
@loongjoe Hello! Ive fixed the inheritance issue In https://github.com/duckdb/duckdb-vss/pull/59
